# Generated by Django 4.0.4 on 2022-05-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.AddField(
            model_name='topping',
            name='pizza',
            field=models.ManyToManyField(to='pizzas.pizza'),
        ),
    ]
